require("dotenv").config()
require("./core/workers/violationCleanup")()
require("./core/workers/spamCleanup")()
const client = require("./client")
const reputationDecayJob = require("./jobs/reputationDecay")
const cleanRewardJob = require("./jobs/cleanReward")
require("./bootstrap")(client)
require("./core/loops/staffTime.loop")(client)
client.login(process.env.TOKEN)
setInterval(() => { reputationDecayJob().catch(() => {}) }, Number(process.env.REPUTATION_DECAY_INTERVAL_MS || 3600000))
setInterval(() => { cleanRewardJob().catch(() => {}) }, Number(process.env.CLEAN_REWARD_INTERVAL_MS || 3600000))
